# This file was generated by GoReleaser. DO NOT EDIT.
cask "argonaut" do
  name "argonaut"
  desc "A GitOps CLI tool for managing ArgoCD applications"
  homepage "https://github.com/darksworm/argonaut"
  version "2.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "argonaut"

  on_macos do
    on_intel do
      url "https://github.com/darksworm/argonaut/releases/download/v#{version}/argonaut-#{version}-darwin-amd64.tar.gz"
      sha256 "23f29c07c889aa9aa2343c7841dd7517d9224a7ea0489ff6a1d46a1854ad52b1"
    end
    on_arm do
      url "https://github.com/darksworm/argonaut/releases/download/v#{version}/argonaut-#{version}-darwin-arm64.tar.gz"
      sha256 "dc3614166d03add2222b3d77c5dba9471cd7e7cfd1745acbdeb066dfcf701045"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/darksworm/argonaut/releases/download/v#{version}/argonaut-#{version}-linux-amd64.tar.gz"
      sha256 "b862043c5176318f3a98ab0d1b897dd00c923f45490fc9ec008942f79d1f7e38"
    end
    on_arm do
      url "https://github.com/darksworm/argonaut/releases/download/v#{version}/argonaut-#{version}-linux-arm64.tar.gz"
      sha256 "b7503cc309196af90d4bd1106c9df86a695a5ace78e769fad4ed9b16c2b4b05b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/argonaut"]
    end
  end

  caveats do
    "To get started:"
    "  argonaut --help"
  end

  # No zap stanza required
end
