# This file was generated by GoReleaser. DO NOT EDIT.
cask "argonaut" do
  desc "A GitOps CLI tool for managing ArgoCD applications"
  homepage "https://github.com/darksworm/argonaut"
  version "1.10.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "argonaut"

  on_macos do
    on_intel do
      url "https://github.com/darksworm/argonaut/releases/download/v1.10.0/argonaut-1.10.0-darwin-amd64.tar.gz"
      sha256 "78a4a1f31614178719d95826cdeac65679f4e7c5138364409ff4f726c4eadc7b"
    end
    on_arm do
      url "https://github.com/darksworm/argonaut/releases/download/v1.10.0/argonaut-1.10.0-darwin-arm64.tar.gz"
      sha256 "68a5c643c1b09cb7bf81c6a969be9665e10e23d4517828065bb123da3c8f7aa6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/darksworm/argonaut/releases/download/v1.10.0/argonaut-1.10.0-linux-amd64.tar.gz"
      sha256 "d22b89314f08f374038d1767f1acc851f552cf4f512bae89ac5c026ee830948e"
    end
    on_arm do
      url "https://github.com/darksworm/argonaut/releases/download/v1.10.0/argonaut-1.10.0-linux-arm64.tar.gz"
      sha256 "ee1d347f8ff10892d1ad0121142b678f5225d05fce528e19b9a2f45bbc94e758"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/argonaut"]
    end
  end

  caveats do
    "To get started:"
    "  argonaut --help"
  end

  # No zap stanza required
end
