# This file was generated by GoReleaser. DO NOT EDIT.
cask "argonaut" do
  version "2.17.0"

  on_macos do
    on_intel do
      sha256 "785d425f2ccf00f729f835db36975e4b94875d566746342cdaefa83fa1fdde05"
      url "https://github.com/darksworm/argonaut/releases/download/v#{version}/argonaut-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "5a2719cab7d8243a5c8d19926f26f233d756bf9f3f4a7dfcc2ddd0d8815b284d"
      url "https://github.com/darksworm/argonaut/releases/download/v#{version}/argonaut-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bfbd87ec808ea1d8d99d7a4a28cfc1dcbec60626e5305c05340b42f19fd7a7f6"
      url "https://github.com/darksworm/argonaut/releases/download/v#{version}/argonaut-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "11f87a329851b268231d261e9fcd09830a32a8788db94f58b9f7787dc72394ea"
      url "https://github.com/darksworm/argonaut/releases/download/v#{version}/argonaut-#{version}-linux-arm64.tar.gz"
    end
  end

  name "argonaut"
  desc "A GitOps CLI tool for managing ArgoCD applications"
  homepage "https://github.com/darksworm/argonaut"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "argonaut"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/argonaut"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To get started:
      argonaut --help
  EOS
end
