# This file was generated by GoReleaser. DO NOT EDIT.
cask "traefiktop" do
  name "traefiktop"
  desc "A TUI for visualizing Traefik routing"
  homepage "https://github.com/darksworm/traefiktop"
  version "2.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "traefiktop"

  on_macos do
    on_intel do
      url "https://github.com/darksworm/traefiktop/releases/download/v#{version}/traefiktop-#{version}-darwin-amd64.tar.gz"
      sha256 "1232292d3d54b6985563359f7ef33832e63f288fe6b098527b03a62f97617670"
    end
    on_arm do
      url "https://github.com/darksworm/traefiktop/releases/download/v#{version}/traefiktop-#{version}-darwin-arm64.tar.gz"
      sha256 "466ea2a71bd092198ff665ef315323df59d5a044f9051ffcb7ea3f2d2378258e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/darksworm/traefiktop/releases/download/v#{version}/traefiktop-#{version}-linux-amd64.tar.gz"
      sha256 "d1d11a51b9e47cb61a8b1e61d007452799dea40ae7ec61f2cf1871d360d09239"
    end
    on_arm do
      url "https://github.com/darksworm/traefiktop/releases/download/v#{version}/traefiktop-#{version}-linux-arm64.tar.gz"
      sha256 "8ffd2777ebad02e0c220a776cadeb1dadc51cf896beb9a8a4acd1905247800cd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/traefiktop"]
    end
  end

  caveats do
    "To get started:"
    "  traefiktop --help"
  end

  # No zap stanza required
end
