# This file was generated by GoReleaser. DO NOT EDIT.
cask "traefiktop" do
  name "traefiktop"
  desc "A TUI for visualizing Traefik routing"
  homepage "https://github.com/darksworm/traefiktop"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "traefiktop"

  on_macos do
    on_intel do
      url "https://github.com/darksworm/traefiktop/releases/download/v#{version}/traefiktop-#{version}-darwin-amd64.tar.gz"
      sha256 "cd78f8f4904426e98560c744834ea9d2ad888aca3630f35b85cba0bb3d0e8307"
    end
    on_arm do
      url "https://github.com/darksworm/traefiktop/releases/download/v#{version}/traefiktop-#{version}-darwin-arm64.tar.gz"
      sha256 "a4a1ee8ac5f15ffe1e9ecd2fbc253114b010d1970f1468f2a2f62b0d5fdb21a0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/darksworm/traefiktop/releases/download/v#{version}/traefiktop-#{version}-linux-amd64.tar.gz"
      sha256 "6845ba3bd4e721dcdbcfb03be468b4d0a39f2722181e6d9b4809f351a7ba9466"
    end
    on_arm do
      url "https://github.com/darksworm/traefiktop/releases/download/v#{version}/traefiktop-#{version}-linux-arm64.tar.gz"
      sha256 "187df430e4d5917e079472444905c6de84f85c35328677786ba7cbe12a9ca175"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/traefiktop"]
    end
  end

  caveats do
    "To get started:"
    "  traefiktop --help"
  end

  # No zap stanza required
end
