# This file was generated by GoReleaser. DO NOT EDIT.
cask "traefiktop" do
  name "traefiktop"
  desc "A TUI for visualizing Traefik routing"
  homepage "https://github.com/darksworm/traefiktop"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "traefiktop"

  on_macos do
    on_intel do
      url "https://github.com/darksworm/traefiktop/releases/download/v#{version}/traefiktop-#{version}-darwin-amd64.tar.gz"
      sha256 "de561352b2d71437ee7da619b7dc547b3c1e8a32e4082871a1e80d16c133e19b"
    end
    on_arm do
      url "https://github.com/darksworm/traefiktop/releases/download/v#{version}/traefiktop-#{version}-darwin-arm64.tar.gz"
      sha256 "51414818e068288292d7b8a2376ff0756cacc770445130fc35d1601b48cbdb21"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/darksworm/traefiktop/releases/download/v#{version}/traefiktop-#{version}-linux-amd64.tar.gz"
      sha256 "3f4ad0abb172a18da7d3d74d519cf4fe11f134d077249282916de0a807fc2c2e"
    end
    on_arm do
      url "https://github.com/darksworm/traefiktop/releases/download/v#{version}/traefiktop-#{version}-linux-arm64.tar.gz"
      sha256 "e7e5ebb09aaa800aa6ca6611debef6c3173b5c6637043f942a32c298a9382755"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/traefiktop"]
    end
  end

  caveats do
    "To get started:"
    "  traefiktop --help"
  end

  # No zap stanza required
end
