# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitagrip < Formula
  desc "A fast TUI application for discovering, grouping, and inspecting multiple Git repositories"
  homepage "https://github.com/darksworm/gitagrip"
  version "1.0.6"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/darksworm/gitagrip/releases/download/v1.0.6/gitagrip-1.0.6-darwin-amd64.tar.gz"
      sha256 "0246cb3a77b1c1cbb086116cc820e00949bac68b00552f7778aadabf92f67295"

      def install
        bin.install "gitagrip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/darksworm/gitagrip/releases/download/v1.0.6/gitagrip-1.0.6-darwin-arm64.tar.gz"
      sha256 "5b9495ce677371656c2d90ab198d622acc97da9cf0845a529be86488dd41a432"

      def install
        bin.install "gitagrip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/darksworm/gitagrip/releases/download/v1.0.6/gitagrip-1.0.6-linux-amd64.tar.gz"
      sha256 "4ab569000aadf4e3eb5047336a098346ad79905846551bb92c2ada2a56db4616"
      def install
        bin.install "gitagrip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darksworm/gitagrip/releases/download/v1.0.6/gitagrip-1.0.6-linux-arm64.tar.gz"
      sha256 "f25722dc1830a75aabe2bbafdee9fa1492a45aa90a6054cbfbdd8d90bb1bfdd6"
      def install
        bin.install "gitagrip"
      end
    end
  end

  test do
    system "#{bin}/gitagrip", "--version"
  end
end
